version: '3'
services:
  blog:
   #image: node:9-alpine
   build: .
   command: echo 'ready'
   volumes:
    - ./app:/home/app/blog
    - ./app/node_modules:/home/app/blog/node_modules
   ports:
    - "8080:80"
    - "8181:433"
