version: '3'
services:
  blog:
    build:
        context: .
        args:
          workdir: ${WORKDIR}
    command: npm run ${RUN_COMMAND}
    volumes:
      - .:${WORKDIR}
      - ${WORKDIR}/node_modules
    ports:
      - "8080:80"
      - "8181:433"
      - "3000:3000"
    networks:
      - backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@db/${DB_NAME}
  db:
    image: postgres:10-alpine
    restart: always
    volumes:
      - ./postgres/data:/var/lib/postgres/
    expose:
      - "5432"
    networks:
      - backend
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"

networks:
  backend:
    driver: bridge