version: '3'
services:
  db:
    image: postgres:10-alpine
    restart: always
    volumes:
      - ./postgres/data:/var/lib/postgres/
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    ports:
      - "6003:3306"
  blog:
   #image: node:9-alpine
   build: .
   command: echo 'ready'
   volumes:
    - ./app:/home/app/blog
   ports:
    - "8080:80"
    - "8181:433"
  links:
    - db
  depends_on:
    - db
